[package]
name = "cch23-xmas"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.75"
axum = { version = "0.7.1", features = ["macros"] }
axum-extra = { version = "0.9.0", features = ["cookie"] }
base64 = "0.21.5"
serde = { version = "1.0.193", features = ["derive"] }
shuttle-axum = { version = "0.34.1", default-features = false, features = ["axum-0-7"] }
shuttle-runtime = "0.34.1"
tokio = "1.34.0"
tower-http = { version = "0.5.0", features = ["trace"] }
tracing = "0.1.40"
